Re-inclusion of yad for steamtinkerlaunch
getsolus/solus-sc pull request #105
Opened 2021-09-15 18:11 UTC by Staudey

Re-include yad into the repository. Necessary for steamtinkerlaunch. See https://dev.getsol.us/T9674

Diff for yad and steamtinkerlaunch on phab incoming.

My package doesn't create a yad-dbginfo, so I left that one out.

2021-09-17 18:08 UTC, JoshStrobl commented
> My package doesn't create a yad-dbginfo, so I left that one out.

That's because dbginfo generation doesn't happen by default. It happens on the server though. So that needs to be removed as well.

2021-09-17 18:08 UTC, JoshStrobl requested changes
beep boop GitHub requires me to comment something before marking as request changes.

2021-09-17 19:10 UTC, Staudey commented
> That's because dbginfo generation doesn't happen by default. It happens on the server though. So that needs to be removed as well.

Thanks, didn't know about this.

2021-09-27 17:21 UTC, JoshStrobl commented
LGTM, thanks!

2021-09-27 17:21 UTC, merged

2021-09-29 08:24 UTC, frostworx commented
Thank you very much for creating/maintaining the Solus package of my steamtinkerlaunch _(and yad)_, @Staudey!
👍😀

2021-09-29 17:32 UTC, Staudey commented
> Thank you very much for creating/maintaining the Solus package of my steamtinkerlaunch _(and yad)_, @Staudey! :+1: :grinning: 

People were asking for it after all! :smile: 
If there are a lot of weird Solus-related bug reports on your project page, blame me (and inform me so I can fix that :laughing: )

2021-09-29 17:46 UTC, frostworx commented
Hehe, will do 😀 Thanks again!